<?php
/**
 * @file
 * Code for the Locations feature.
 */

include_once 'hr_locations.features.inc';

/**
 * Implement hook_taxonomy_term_presave($term)
 * Calculates and adds the admin level in a field to the term so that it
 * can be stored in the database.
 */
function hr_locations_taxonomy_term_presave($term) {
  if (empty($term->field_loc_admin_level[LANGUAGE_NONE])) {
    // Get term parents
    $parents = taxonomy_get_parents($term->tid);
    $term->field_loc_admin_level[LANGUAGE_NONE] = array(array('value' => count($parents)));
  }
}

